### ISSUE TITLE
setState 

### ISSUE THREAD

**Issue by iansparks** [dewball345/Breact#3]
Hi. In your setState you do this:

```
    def setState(self, attrs, one_state_change=False):
        for attr in attrs.keys():
            self.state[attr] = attrs[attr]
```

Did you compare the performance of using dict.update() ?

```
    def setState(self, attrs, one_state_change=False):
        self.state.update(attrs) 
```

**Comment by dewball345** [comment]
Hey, i didn't know about dict.update(), it seems really nice! Will change it

**Comment by iansparks** [comment]
I thought some more. If you use state.update() you will lose the ability to know if the state really changed. i.e. if state = {"a" : 1} and someone does self.setState({'a' : 1}) then there is no change so why do any repaint?

**Comment by dewball345** [comment]
Oh yeah, that's true. Also, btw I implemented a simple dom diffing
algorithm. You can check it out in /breact/baseclasses.py

**Comment by dewball345** [comment]
ok, i added some code to check if the state actually updated; if it didn't
nothing will be returned.

**Comment by dewball345** [comment]
Okay, i removed the "check if state actually changed", because sometimes you just need the content to reload(for example, check my router class)
